rotel_send_command:
  name: Send Command
  description: "Send a command to a Rotel device."
  fields:
    command_name:
      name: Command Name
      description: >-
        Command name.
        See rsp1570serial module commands.py for available commands.
      example: 'POWER_TOGGLE'
    entity_id:
      name: Entity ID
      description: Name(s) of the entities to set (or 'all')
      example: 'media_player.rotel'
rotel_reconnect:
  name: Re-connect
  description: "Reconnect to a Rotel device that may have been disconnected."
  fields:
    entity_id:
      name: Entity ID
      description: Name(s) of the entities to set (or 'all')
      example: 'media_player.rotel'
