- alias: Rotel RSP-1570 Volume Up
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: VOLUME_UP
  action:
    service: media_player.volume_up
    entity_id: media_player.rotel_rsp_1570
- alias: Rotel RSP-1570 Volume Down
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: VOLUME_DOWN
  action:
    service: media_player.volume_down
    entity_id: media_player.rotel_rsp_1570
