name: Validate with hassfest and HACS

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  validate-hass:
    name: Hassfest validation
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v3"
        - uses: "home-assistant/actions/hassfest@master"
  validate-hacs:
    runs-on: "ubuntu-latest"
    name: HACS validation
    steps:
      - uses: "actions/checkout@v3"
      - uses: "hacs/action@main"
        with:
          category: "integration"
